### ISSUE TITLE
unittest Errors

### ISSUE THREAD

**Issue by Reed97123** [Netflix/vmaf#120]
Installed as per the instructions on Ubuntu 16.04.  Upon running unittest I received some Failures/Errors.  

Should I be concerned about these Errors/Failures?  Thanks!

======================================================================
ERROR: local_explainer_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: local_explainer_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/root/vmaf/python/test/local_explainer_test.py", line 9, in <module>
    from vmaf.core.local_explainer import LocalExplainer
  File "/root/vmaf/python/src/vmaf/core/local_explainer.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/root/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

======================================================================
ERROR: routine_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: routine_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/root/vmaf/python/test/routine_test.py", line 5, in <module>
    from vmaf.routine import train_test_vmaf_on_dataset, read_dataset, run_test_on_dataset, generate_dataset_from_raw
  File "/root/vmaf/python/src/vmaf/routine.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/root/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

======================================================================
ERROR: cross_validation_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: cross_validation_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/root/vmaf/python/test/cross_validation_test.py", line 12, in <module>
    from vmaf.routine import read_dataset
  File "/root/vmaf/python/src/vmaf/routine.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/root/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

======================================================================
ERROR: train_test_model_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: train_test_model_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/root/vmaf/python/test/train_test_model_test.py", line 12, in <module>
    from vmaf.routine import read_dataset
  File "/root/vmaf/python/src/vmaf/routine.py", line 6, in <module>
    from matplotlib import pyplot as plt
  File "/root/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/root/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

======================================================================
FAIL: test_run_cleaning_cache_psnr (command_line_test.CommandLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/command_line_test.py", line 102, in test_run_cleaning_cache_psnr
    ret = run_process(cmd, shell=True)
  File "/root/vmaf/python/src/vmaf/tools/misc.py", line 379, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /root/vmaf/run_testing PSNR /root/vmaf/python/test/resource/example_dataset.py --parallelize --cache-result --suppress-plot

======================================================================
FAIL: test_run_testing_psnr (command_line_test.CommandLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/command_line_test.py", line 45, in test_run_testing_psnr
    ret = run_process(cmd, shell=True)
  File "/root/vmaf/python/src/vmaf/tools/misc.py", line 379, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /root/vmaf/run_testing PSNR /root/vmaf/python/test/resource/example_dataset.py --parallelize --suppress-plot

======================================================================
FAIL: test_run_testing_vmaf (command_line_test.CommandLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/command_line_test.py", line 31, in test_run_testing_vmaf
    ret = run_process(cmd, shell=True)
  File "/root/vmaf/python/src/vmaf/tools/misc.py", line 379, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /root/vmaf/run_testing VMAF /root/vmaf/python/test/resource/example_dataset.py --parallelize --suppress-plot

======================================================================
FAIL: test_run_testing_vmaf_raw_dataset (command_line_test.CommandLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/command_line_test.py", line 38, in test_run_testing_vmaf_raw_dataset
    ret = run_process(cmd, shell=True)
  File "/root/vmaf/python/src/vmaf/tools/misc.py", line 379, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /root/vmaf/run_testing VMAF /root/vmaf/python/test/resource/example_raw_dataset.py --parallelize --suppress-plot

======================================================================
FAIL: test_run_vmaf_training (command_line_test.CommandLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/command_line_test.py", line 55, in test_run_vmaf_training
    ret = run_process(cmd, shell=True)
  File "/root/vmaf/python/src/vmaf/tools/misc.py", line 379, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /root/vmaf/run_vmaf_training /root/vmaf/python/test/resource/example_dataset.py /root/vmaf/python/test/resource/vmaf_v4.py /root/vmaf/python/test/resource/vmaf_v4.py /root/vmaf/workspace/workdir/tmp.pkl --parallelize --suppress-plot

======================================================================
FAIL: test_run_vmaf_training_raw_dataset (command_line_test.CommandLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/command_line_test.py", line 65, in test_run_vmaf_training_raw_dataset
    ret = run_process(cmd, shell=True)
  File "/root/vmaf/python/src/vmaf/tools/misc.py", line 379, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /root/vmaf/run_vmaf_training /root/vmaf/python/test/resource/example_raw_dataset.py /root/vmaf/python/test/resource/vmaf_v4.py /root/vmaf/python/test/resource/vmaf_v4.py /root/vmaf/workspace/workdir/tmp.pkl --parallelize --suppress-plot

======================================================================
FAIL: test_run_vmaf_runner_pool_perc10 (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/quality_runner_test.py", line 933, in test_run_vmaf_runner_pool_perc10
    self.assertAlmostEqual(results[0]['VMAF_score'], 72.753572476835515, places=4)
AssertionError: 72.753852967634373 != 72.75357247683552 within 4 places

======================================================================
FAIL: test_run_vmafossexec_runner_enable_avx_precise (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/vmaf/python/test/quality_runner_test.py", line 1375, in test_run_vmafossexec_runner_enable_avx_precise
    self.assertAlmostEqual(results[0]['VMAFOSSEXEC_score'], 76.699266666666674, places=5)
AssertionError: 76.699306249999992 != 76.69926666666667 within 5 places

----------------------------------------------------------------------
Ran 229 tests in 2144.253s

FAILED (failures=8, errors=4)

**Comment by li-zhi** [comment]
The 4 errors are related to the package python-tk. They can probably be fixed by installing that package. The first 6 failures are due to that the command lines returns 1 instead of 0. But the underlying classes have been tested by other test cases, so it's probably OK. The last 2 failures due to slight numerical difference are ignorable.
