### ISSUE TITLE
Getting an error while running .\unittest on Ubuntu 

### ISSUE THREAD

**Issue by singhalhimanshu941** [Netflix/vmaf#135]
error : vmaf-master/feature/ms_ssim does not exist, did you build?

**Comment by singhalhimanshu941** [comment]
full traceback : 
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vmaf-master/python/src/vmaf/tools/misc.py", line 267, in func_wrapper
    executor = func(args)
  File "/home/vmaf-master/python/src/vmaf/core/executor.py", line 119, in _run
    result = self._run_on_asset(asset)
  File "/home/vmaf-master/python/src/vmaf/core/executor.py", line 291, in _run_on_asset
    self._generate_result(asset)
  File "/home/vmaf-master/python/src/vmaf/core/feature_extractor.py", line 480, in _generate_result
    ExternalProgramCaller.call_ms_ssim(yuv_type, ref_path, dis_path, w, h, log_file_path, logger)
  File "/home/vmaf-master/python/src/vmaf/__init__.py", line 85, in call_ms_ssim
    ms_ssim=required(ExternalProgram.ms_ssim),
  File "/home/vmaf-master/python/src/vmaf/__init__.py", line 20, in required
    raise AssertionError("%s does not exist, did you build?" % (path))
AssertionError: /home/vmaf-master/feature/ms_ssim does not exist, did you build?

**Comment by li-zhi** [comment]
Make sure that ‘make’ succeeds without error messages.

**Comment by singhalhimanshu941** [comment]
when i run make i got an error : 
In file included from /home/main_workspace/vmaf-master/wrapper/../feature/src/adm_tools.c:32:0:
/usr/lib/gcc/i686-linux-gnu/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"
 # error "SSE2 instruction set not enabled"

**Comment by li-zhi** [comment]
This should do with the processor. Make sure it is SSE2 enabled.

**Comment by dcoolz** [comment]
Yes it was due to the processor. I was using AMD so it was not able to get sse2 instruction set. It worked for me with Intel Pentium

**Comment by singhalhimanshu941** [comment]
Yes it was the processor issue. I was using AMD so it was throwing sse2 instruction set not enabled. Its working fine now for me with Intel Pentium.
