### ISSUE TITLE
ffmpeg2vmaf cannot find ffmpeg?

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#137]
Trying to run `ffmpeg2vmaf` with the latest version of VMAF under macOS 10.12 and ffmpeg installed via Homebrew, I get an error about ffmpeg not being found:

```
$ ./ffmpeg2vmaf 1920 1080 ~/Downloads/test-movies/{out-h264-crf17.mp4,out-h265-crf23.mp4}
Traceback (most recent call last):
  File "./ffmpeg2vmaf", line 182, in <module>
    ret = main()
  File "./ffmpeg2vmaf", line 142, in main
    optional_dict2=None,
  File "/Users/werner/Documents/Projects/vmaf/python/src/vmaf/core/executor.py", line 68, in __init__
    self._assert_assets()
  File "/Users/werner/Documents/Projects/vmaf/python/src/vmaf/core/executor.py", line 146, in _assert_assets
    self._assert_an_asset(asset)
  File "/Users/werner/Documents/Projects/vmaf/python/src/vmaf/core/executor.py", line 174, in _assert_an_asset
    VmafExternalConfig.get_and_assert_ffmpeg()
  File "/Users/werner/Documents/Projects/vmaf/python/src/vmaf/config.py", line 64, in get_and_assert_ffmpeg
    assert path is not None, cls._MISSING_EXTERNAL_MESSAGE.format(name='ffmpeg', key='FFMPEG_PATH')
AssertionError:
    Must install ffmpeg and set FFMPEG_PATH in /Users/werner/Documents/Projects/vmaf/python/src/vmaf/externals.py, e.g. add a line like
    FFMPEG_PATH = "[path to exec]/ffmpeg"
```

I did set `$FFMPEG_PATH` – but I don't know why it would be necessary since the program could just search for an `ffmpeg` binary in `$PATH` (it is included there).

```
$ echo $FFMPEG_PATH
/usr/local/bin/ffmpeg
```

Looking at the file `externals.py`, I see some hardcoded paths though:

```
FFMPEG_PATH = '/home/zli/Projects/stash/MCE/transcoder/builds/bin/ffmpeg'
MATLAB_PATH = '/usr/local/MATLAB/R2014b/bin/matlab'
```

But I assume this is just an example?

What could cause the error? Am I missing some steps?

**Comment by slhck** [comment]
Oh, I get it now, I have to:

* create a file `python/src/vmaf/externals.py`
* add the line `FFMPEG_PATH = "/usr/local/bin/ffmpeg"`

Should this be added to the README?
