### ISSUE TITLE
Python error 

### ISSUE THREAD

**Issue by SGShen** [Netflix/vmaf#169]
An error in "run_vmaf" happens from time to time. It happens randomly when invoke "./run_vmaf" in a loop. It seems a python problem.

Traceback (most recent call last):
  File "./run_vmaf", line 143, in <module>
    ret = main()
  File "./run_vmaf", line 107, in main
    runner.run()
  File "/home/sg/tools/vmaf/vmaf-1.3.5/python/src/vmaf/core/executor.py", line 125, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/sg/tools/vmaf/vmaf-1.3.5/python/src/vmaf/core/quality_runner.py", line 304, in _run_on_asset
    vmaf_fassembler.run()
  File "/home/sg/tools/vmaf/vmaf-1.3.5/python/src/vmaf/core/feature_assembler.py", line 82, in run
    runner.run(parallelize=self.parallelize)
  File "/home/sg/tools/vmaf/vmaf-1.3.5/python/src/vmaf/core/executor.py", line 125, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/sg/tools/vmaf/vmaf-1.3.5/python/src/vmaf/core/executor.py", line 332, in _run_on_asset
    result = self._post_process_result(result)
  File "/home/sg/tools/vmaf/vmaf-1.3.5/python/src/vmaf/core/feature_extractor.py", line 170, in _post_process_result
    (np.array(result.result_dict[adm_den_scores_key]) + cls.ADM2_CONSTANT)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "batch_evaluate_vmaf.py", line 107, in <module>
    output = subprocess.check_output(args).decode('utf-8')
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)

**Comment by christosbampis** [comment]
It looks like the denominator for the ADM feature was not calculated correctly and it returned None. You could place a break point and see why the result dictionary (result_dict) does not have a valid value for that key.

**Comment by li-zhi** [comment]
```
(np.array(result.result_dict[adm_den_scores_key]) + cls.ADM2_CONSTANT)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
It seems that the c executable hasn't generated results correctly. Since you run `run_vmaf` in a loop, I suspect that there are collisions in the intermediate files generated. I would recommend using `wrapper/vmafossexec` instead. See https://github.com/Netflix/vmaf#vmafossexec---python-independent-implementation

**Comment by SGShen** [comment]
@li-zhi , @christosbampis, Thank you for your replies! I will try the wrapper later.

For now, does it help if I put some time gap in between the "./run_vmaf"? Also, for those successful "./run_vmaf", can I still trust the generated scores?

**Comment by li-zhi** [comment]
It is really hard to tell, unless one digs into it to see what happened.

**Comment by SGShen** [comment]
@li-zhi, I tried "vmafossexec" -- it is a lot faster than run_vmaf. But I noticed the SSIM, PSNR are different from the results from VQMT. Especially SSIM, the difference is somewhat big -- 0.99 vs. 0.89 (VQMT).  Would it be the formulas used by VMAF is not the same as that in VQMT? Thanks.

**Comment by li-zhi** [comment]
There is an explanation on SSIM in the FAQ page at:
https://github.com/Netflix/vmaf/blob/master/FAQ.md
