### ISSUE TITLE
test_run_vamf_legacy_runner_10le (quality_runner_test.QualityRunnerTest) failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by cvley** [Netflix/vmaf#2]
```
======================================================================
ERROR: test_run_vamf_legacy_runner_10le (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cvley/vmaf/python/test/quality_runner_test.py", line 94, in test_run_vamf_legacy_runner_10le
    self.runner.run()
  File "/home/cvley/vmaf/python/core/executor.py", line 62, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/cvley/vmaf/python/core/quality_runner.py", line 172, in _run_on_asset
    vmaf_fassembler.run()
  File "/home/cvley/vmaf/python/core/feature_assembler.py", line 70, in run
    optional_dict=self.optional_dict,
  File "/home/cvley/vmaf/python/core/executor.py", line 406, in run_executors_in_parallel
    executors = map(run_executor, list_args)
  File "/home/cvley/vmaf/python/core/executor.py", line 381, in run_executor
    executor.run()
  File "/home/cvley/vmaf/python/core/executor.py", line 62, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/cvley/vmaf/python/core/executor.py", line 188, in _run_on_asset
    self._prepare_log_file(asset)
  File "/home/cvley/vmaf/python/core/executor.py", line 115, in _prepare_log_file
    with open(log_file_path, 'wt') as log_file:
IOError: [Errno 36] File name too long: '/home/cvley/vmaf/workspace/workdir/664701be-de8b-46c3-a0fc-ba685bd9652e/VMAF_feature_V0.2.1_test_0_0_src01_hrc00_576x324.yuv422p10le_576x324_yuv422p10le_vs_src01_hrc01_576x324.yuv422p10le_576x324_yuv422p10le_q_576x324'
```

With some tests and google, I think it was caused by ecryptfs which file length maximum number is less than 144. Hope you can deal with it, thanks 😃

**Comment by zli-nflx** [comment]
Will be looking into this...

**Comment by zli-nflx** [comment]
@cvley: I created a branch:
https://github.com/Netflix/vmaf/tree/bugfix/issue%232
See if it fixes your problem.

**Comment by cvley** [comment]
@zli-nflx this branch fixed this problem, thanks.
