### ISSUE TITLE
ffmpeg2vmaf coredumps

### ISSUE THREAD

**Issue by sridhard** [Netflix/vmaf#223]
Hi,

I get the following error when I run ffmpeg2vmaf

Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
Output #0, rawvideo, to '/home/ubuntu/VMAF/vmaf/workspace/workdir/e7507b45-aa5e-42c5-a2b4-a9e6de3b210e/dis_cmd_8041123613741203_8041123613741203_test_orig_notyuv_vs_peer1_notyuv_q_1280x720':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.40.101
    Stream #0:0(und): Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 24 fps, 24 tbn, 24 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc56.60.100 rawvideo
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> rawvideo (native))
Press [q] to stop, [?] for help
frame=  962 fps=3.8 q=-0.0 Lsize= 1298700kB time=00:00:40.12 bitrate=265145.2kbits/s    
video:1298700kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
av_interleaved_write_frame(): Broken pipe
frame=  963 fps=3.8 q=-0.0 Lsize= 1300050kB time=00:00:33.05 bitrate=322225.4kbits/s    
video:1300050kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Conversion failed!
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/core/executor.py", line 434, in _open_ref_workfile
    run_process(ffmpeg_cmd, shell=True)
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/tools/misc.py", line 409, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /usr/bin/ffmpeg  -i test_orig.mp4 -an -vsync 0 -pix_fmt yuv420p  -vf scale=1280x720 -f rawvideo -sws_flags bicubic -y /home/ubuntu/VMAF/vmaf/workspace/workdir/e7507b45-aa5e-42c5-a2b4-a9e6de3b210e/ref_cmd_8041123613741203_8041123613741203_test_orig_notyuv_vs_peer1_notyuv_q_1280x720
Traceback (most recent call last):
  File "./ffmpeg2vmaf", line 191, in <module>
    ret = main()
  File "./ffmpeg2vmaf", line 155, in main
    runner.run()
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/core/executor.py", line 125, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/core/quality_runner.py", line 309, in _run_on_asset
    vmaf_fassembler.run()
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/core/feature_assembler.py", line 83, in run
    runner.run(parallelize=self.parallelize)
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/core/executor.py", line 125, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/core/executor.py", line 332, in _run_on_asset
    result = self._post_process_result(result)
  File "/home/ubuntu/VMAF/vmaf/python/src/vmaf/core/feature_extractor.py", line 185, in _post_process_result
    / np.array(result.result_dict[vif_den_scale0_scores_key]))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by li-zhi** [comment]
@sridhard The error message seems cryptic and it is hard to figure out what went wrong unless one can reproduce it. Moving forward the blessed way to run VMAF on non-YUV videos is FFmpeg + libvmaf as a filter. See: https://ffmpeg.org/ffmpeg-filters.html#libvmaf
