### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by kanza-ali** [Netflix/vmaf#233]
I am using Ubuntu 16 and want to install vmaf 
When I do ./unittest

FAIL: test_run_vmaf_training_raw_dataset (command_line_test.CommandLineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kanza/Downloads/vmaf-master/python/test/command_line_test.py", line 66, in test_run_vmaf_training_raw_dataset
    ret = run_process(cmd, shell=True)
  File "/home/kanza/Downloads/vmaf-master/python/src/vmaf/tools/misc.py", line 409, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 1, cmd: /home/kanza/Downloads/vmaf-master/run_vmaf_training /home/kanza/Downloads/vmaf-master/python/test/resource/example_raw_dataset.py /home/kanza/Downloads/vmaf-master/python/test/resource/vmaf_v4.py /home/kanza/Downloads/vmaf-master/python/test/resource/vmaf_v4.py /home/kanza/Downloads/vmaf-master/workspace/workdir/tmp.pkl --parallelize --suppress-plot

----------------------------------------------------------------------
Ran 125 tests in 51.472s

FAILED (failures=12, errors=11)

**Comment by slhck** [comment]
What happens if you run a simple VMAF command according to https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md#basic-usage?

**Comment by slhck** [comment]
"Not working" is not a proper error description. Please show exactly what you are typing and what happens.

**Comment by kanza-ali** [comment]
Thank you for your reply and help. The error is:

ImportError: No module named vmaf.config 

When I am following these steps for installation given here:

https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md#basic-usage

I run "make" the output is

make[1]: Entering directory '/home/kanza/Downloads/vmaf/libsvm'
if [ "Linux" = "Darwin" ]; then \
	SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so.2"; \
else \
	SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.2"; \
fi; \
g++ ${SHARED_LIB_FLAG} svm.o -o libsvm.so.2
make[1]: Leaving directory '/home/kanza/Downloads/vmaf/libsvm'

**Comment by kanza-ali** [comment]
hi @slhck 

I have successfully installed the VMAF. While I am trying to find the psnr of video, I have following error

Traceback (most recent call last):
  File "./run_vmaf", line 8, in <module>
    from vmaf.config import VmafConfig, DisplayConfig
ImportError: No module named 'vmaf'

**Comment by kanza-ali** [comment]
I have open ~/.bashrc by vim and added 
export PATH="$PATH:$HOME/.local/bin"
at the end of the file. but I think I am missing something.

**Comment by kanza-ali** [comment]
I am using python3 and checked the path by "where python3"

whereis python3
python3: /usr/bin/python3 /usr/bin/python3.5m /usr/bin/python3.5-config /usr/bin/python3.5m-config /usr/bin/python3.5 /usr/lib/python3 /usr/lib/python3.5 /etc/python3 /etc/python3.5 /usr/local/lib/python3.5 /usr/include/python3.5m /usr/include/python3.5 /usr/share/python3 /usr/share/man/man1/python3.1.gz

how to fix this?

**Comment by slhck** [comment]
That's the executable path – I was referring to the Python module path. Have you followed the instructions here, particularly the ones with PYTHONPATH?

https://github.com/Netflix/vmaf/blob/master/resource/doc/VMAF_Python_library.md#installation

**Comment by kanza-ali** [comment]
OK resolved the issue.

**Comment by kanza-ali** [comment]
I am using ubuntu16 and python3, So how to resolve this error

File "/home/kanza/Downloads/vmaf/python/src/vmaf/tools/scanf.py", line 176, in <module>
    from sets import Set
ImportError: No module named 'sets'

**Comment by slhck** [comment]
Glad you got it working.
What you're showing seems like an unneeded line of code.

@li-zhi – I'd propose removing the import, as Python 2.7 and above should already import `set`.

**Comment by kanza-ali** [comment]
I am not getting you, you propose me to remove import from scanf.py file?

**Comment by slhck** [comment]
No, I've asked the main developer to remove it. I may also provide a Pull Request later. At least it seems to me that the import is breaking things with more recent Python versions.

In the meantime, I recommend calling VMAF with Python 2.7.

**Comment by kanza-ali** [comment]
OK 
Thank you so much for all your help and guidance.

**Comment by slhck** [comment]
Please do not ask unrelated questions in one thread.

YUV is needed because VMAF is just comparing pixels. For parsing different video formats, VMAF would have to implement many decoders, which is not practical. You can use VMAF in FFmpeg in order to compare different formats. See: https://ffmpeg.org/ffmpeg-filters.html#libvmaf and https://github.com/Netflix/vmaf/blob/master/resource/doc/libvmaf.md

**Comment by slhck** [comment]
I get it now – VMAF is not Python3-compatible at all. So please stick to Python 2.7.

**Comment by kanza-ali** [comment]
:( 

My FFmpeg is installed python3 and wanted to usee VAMF for batch of videos to know the PSNR

**Comment by slhck** [comment]
I don't quite understand. ffmpeg does not have anything to do with Python. Does your system have Python 2.7? If so, I recommend following the guide here: https://github.com/Netflix/vmaf/blob/master/resource/doc/libvmaf.md

Then compiling ffmpeg with `--enable-libvmaf` according to the compilation guide: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

**Comment by kanza-ali** [comment]
I have enabled libvmaf for FFmpeg. 
I want to see PSNR per frame of a compressed video.

**Comment by slhck** [comment]
If you only want PSNR, you do not need VMAF: http://ffmpeg.org/ffmpeg-filters.html#psnr

Or you calculate both at the same time:

    ffmpeg -i main.mpg -i ref.mpg -lavfi libvmaf="psnr=1:enable-transform=1" -f null -

If your original issue was resolved, please close this thread. Thank you!

**Comment by li-zhi** [comment]
@slhck Unfortunately currently VMAF only supports Python 2. Given the current momentum in Python 3, we might soon like to migrate VMAF to Python 3. Help would be very much appreciated.

**Comment by slhck** [comment]
Yeah, I noticed when I tried to update the `scanf.py` file that many other things needed to be fixed — and a simple `2to3` call doesn't do it. I'm happy to look into it as soon as I find some time.

In fact, I think that it's well worth the effort to migrate these kinds of projects and get into a habit of defaulting to Python 3, as most things are backward-compatible.

**Comment by slhck** [comment]
I propose closing this in favor of #331.

**Comment by NagabhushanSN95** [comment]
> I get it now – VMAF is not Python3-compatible at all. So please stick to Python 2.7.

Since this statement is quite old, can you please revalidate this. v1.5.1 works with Python3, right? Or does it still have many bugs? Do you recommend to use VMAF-v1.3.* with python 2.7 or VMAF-v1.5.1 with Python 3.7?

**Comment by slhck** [comment]
Yeah, Python 3 works and Python 2 support will be dropped soon. Stick to the most recent version.
