### ISSUE TITLE
syntax error in ./unittest

### ISSUE THREAD

**Issue by eexyzhang** [Netflix/vmaf#27]
With some errors after 'make' (ticket #26), I tried ./unittest. I got the following errors:

----------------------------------
Etest on running dis YUV raw video extractor...
.test on running dis YUV raw video extractor in parallel (disabled)...
.test on running asset extractor...
..........test on file system result store save and load...
.test on result aggregate scores...
.test on result to/from dataframe...
....Stats on training data: (SRCC: 0.949, PCC: 0.919, RMSE: 9.776)
..test extra trees train and predict...
.test libsvmnusvr train and predict...
.test random forest train and predict...
.test train, save, load and predict...
.test libsvmnusvr train, save, load and predict...
.......
======================================================================
ERROR: test_run_vmafossexec_runner (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abc/Netflix_VMAF/vmaf/python/test/quality_runner_test.py", line 510, in test_run_vmafossexec_runner
    self.runner.run()
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 81, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 228, in _run_on_asset
    result = self._read_result(asset)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 60, in _read_result
    result.update(self._get_quality_scores(asset))
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 416, in _get_quality_scores
    tree = ElementTree.parse(log_file_path)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0

======================================================================
ERROR: test_run_vmafossexec_runner_norm_type_none (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abc/Netflix_VMAF/vmaf/python/test/quality_runner_test.py", line 561, in test_run_vmafossexec_runner_norm_type_none
    self.runner.run()
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 81, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 228, in _run_on_asset
    result = self._read_result(asset)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 60, in _read_result
    result.update(self._get_quality_scores(asset))
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 416, in _get_quality_scores
    tree = ElementTree.parse(log_file_path)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0

======================================================================
ERROR: test_run_vmafossexec_runner_yuv422p10le (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abc/Netflix_VMAF/vmaf/python/test/quality_runner_test.py", line 611, in test_run_vmafossexec_runner_yuv422p10le
    self.runner.run()
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 81, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 228, in _run_on_asset
    result = self._read_result(asset)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 60, in _read_result
    result.update(self._get_quality_scores(asset))
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 416, in _get_quality_scores
    tree = ElementTree.parse(log_file_path)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/Users/abc/software/anaconda2/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: syntax error: line 1, column 0

----------------------------------------------------------------------
Ran 104 tests in 215.684s

FAILED (errors=3)

**Comment by li-zhi** [comment]
@eexyzhang This should be fixed once the make is successful.

**Comment by eexyzhang** [comment]
You are right. The unittest passes successfully now. Thanks!
