### ISSUE TITLE
run_vmaf gives error on 1080p videos

### ISSUE THREAD

**Issue by deepwilson** [Netflix/vmaf#401]
Running the following command:

`./run_vmaf yuv420p 1920 1080         "datasets/VPAD/TV Episodes/AdaptationTrailer_S02.yuv"          "datasets/VPAD/TV Episodes/AdaptationTrailer_S02_downscaled_sr.yuv"        --out-fmt json`

gives the following error:

`Traceback (most recent call last):
  File "./run_vmaf", line 164, in <module>
    ret = main()
  File "./run_vmaf", line 124, in main
    runner.run()
  File "vmaf/python/src/vmaf/core/executor.py", line 126, in run
    self.results = list(map(self._run_on_asset, self.assets))
  File "vmaf/python/src/vmaf/core/quality_runner.py", line 311, in _run_on_asset
    vmaf_fassembler.run()
  File "vmaf/python/src/vmaf/core/feature_assembler.py", line 84, in run
    runner.run(parallelize=self.parallelize)
  File "vmaf/python/src/vmaf/core/executor.py", line 126, in run
    self.results = list(map(self._run_on_asset, self.assets))
  File "vmaf/python/src/vmaf/core/executor.py", line 292, in _run_on_asset
    self._generate_result(asset)
  File "vmaf/python/src/vmaf/core/feature_extractor.py", line 153, in _generate_result
    ExternalProgramCaller.call_vmaf_feature(yuv_type, ref_path, dis_path, w, h, log_file_path, logger)
  File "vmaf/python/src/vmaf/__init__.py", line 137, in call_vmaf_feature
    run_process(vmaf_feature_cmd, shell=True)
  File "vmaf/python/src/vmaf/__init__.py", line 29, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 2, cmd: vmaf/libvmaf/build/tools/vmaf all yuv420p datasets/VPAD/TV Episodes/AdaptationTrailer_S02.yuv datasets/VPAD/TV Episodes/AdaptationTrailer_S02_downscaled_sr.yuv 1920 1080 >> vmaf/workspace/workdir/23b9a2b3-efdc-45de-9664-20586d9c4b6c/VMAF_feature_V0.2.4c_3c53a8ba3f137a4bfd7c73510a7277982d003592`

**The same command works with 720p videos.**

The unit test also run successfully:

`Ran 297 tests in 208.967s
OK (skipped=1)`
    
What could be the issue?
Please let me know if any other information is required.

**Comment by deepwilson** [comment]
The file name had spaces within. Looks like an error from my side. Though it would be great if the error message could be a bit more detailed.
