### ISSUE TITLE
ImprtError:Failed to import module:feature_test

### ISSUE THREAD

**Issue by xbfhuawei** [Netflix/vmaf#5]
Hi,
    I am tring to test the modle,but when  I have finished to install the  numpy/scipy/matplotlib/pandas packages and run ./unittest,the err ocurrs.
![Uploading image.png…]()
Do u know why?

**Comment by xbfhuawei** [comment]
The err :
ERROR: train_test_model_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: train_test_model_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/train_test_model_test.py", line 10, in <module>
    import config
ImportError: No module named config

**Comment by zli-nflx** [comment]
The error suggests that the [root]/python directory has not been added to
PYTHONPATH, thus it cannot find the [root]/python/config.py file. Please
follow the instruction in README.md to properly add the directory.

**Comment by xbfhuawei** [comment]
Hi ,
    Now the [root]/python directory has been added to PYTHONPATH .Bti still have errs:

File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 66, in test_ansnr
    score, scores = read_log(self.LOG_FILENAME, "ansnr")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_motion (feature_test.FeatureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 78, in test_motion
    score, scores = read_log(self.LOG_FILENAME, "motion")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_psnr (feature_test.FeatureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 162, in test_psnr
    score, scores = read_log(self.LOG_FILENAME, "psnr")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_vif (feature_test.FeatureTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 88, in test_vif
    score, scores = read_log(self.LOG_FILENAME, "vif")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_2nd_moment (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 328, in test_2nd_moment
    score, scores = read_log(self.LOG_FILENAME, "1stmoment")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_adm (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 206, in test_adm
    score, scores = read_log(self.LOG_FILENAME, "adm")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_all (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 274, in test_all
    score, scores = read_log(self.LOG_FILENAME, "vif")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_ansnr (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 220, in test_ansnr
    score, scores = read_log(self.LOG_FILENAME, "ansnr")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_motion (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 232, in test_motion
    score, scores = read_log(self.LOG_FILENAME, "motion")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_psnr (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 316, in test_psnr
    score, scores = read_log(self.LOG_FILENAME, "psnr")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

======================================================================
ERROR: test_vif (feature_test.FeatureTestYuv422p10le)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 242, in test_vif
    score, scores = read_log(self.LOG_FILENAME, "vif")
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 22, in read_log
    score = sum(scores) / float(len(scores))
ZeroDivisionError: float division by zero

----------------------------------------------------------------------
Ran 19 tests in 0.044s

FAILED (errors=19)
Run tests in python/test...
test on running PSNR quality runner in parallel...
Fatal error has occured during the function execution
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/pp/ppworker.py", line 96, in run
    __args = pickle.loads(__sargs)
  File "/root/Desktop/vmaf-master/python/dill/dill.py", line 209, in loads
    return load(file)
  File "/root/Desktop/vmaf-master/python/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/root/Desktop/vmaf-master/python/dill/dill.py", line 278, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
  File "/root/Desktop/vmaf-master/python/core/quality_runner.py", line 14, in <module>
    from core.train_test_model import TrainTestModel
  File "/root/Desktop/vmaf-master/python/core/train_test_model.py", line 11, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1-py2.7-linux-i686.egg/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1-py2.7-linux-i686.egg/pandas/compat/numpy/__init__.py", line 25, in <module>
    'this pandas version'.format(_np_version))
ImportError: this version of pandas is incompatible with numpy < 1.7.0
your numpy version is 1.6.1.
Please upgrade numpy to >= 1.7.0 to use this pandas version
Fatal error has occured during the function execution
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/pp/ppworker.py", line 96, in run
    __args = pickle.loads(__sargs)
  File "/root/Desktop/vmaf-master/python/dill/dill.py", line 209, in loads
    return load(file)
  File "/root/Desktop/vmaf-master/python/dill/dill.py", line 199, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/root/Desktop/vmaf-master/python/dill/dill.py", line 278, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
  File "/root/Desktop/vmaf-master/python/core/quality_runner.py", line 14, in <module>
    from core.train_test_model import TrainTestModel
  File "/root/Desktop/vmaf-master/python/core/train_test_model.py", line 11, in <module>
    import pandas as pd
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1-py2.7-linux-i686.egg/pandas/__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.18.1-py2.7-linux-i686.egg/pandas/compat/numpy/__init__.py", line 25, in <module>
    'this pandas version'.format(_np_version))
ImportError: this version of pandas is incompatible with numpy < 1.7.0
your numpy version is 1.6.1.
Please upgrade numpy to >= 1.7.0 to use this pandas version
Etest on running VMAF quality runner in parallel with custom model...
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/pp/pp.py", line 766, in __run
    sresult = worker.t.receive()
  File "/root/Desktop/vmaf-master/python/pp/pptransport.py", line 132, in receive
    msg_len = struct.unpack("!Q", size_packed)[0]
struct.error: unpack requires a string argument of length 8
Unhandled exception in thread started by <bound method Server.__run of <pp.pp.Server object at 0xb38644c>>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/pp/pp.py", line 766, in __run
  File "/root/Desktop/vmaf-master/python/pp/pp.py", line 775, in __run
    sresult = worker.t.receive()
  File "/root/Desktop/vmaf-master/python/pp/pptransport.py", line 132, in receive
        msg_len = struct.unpack("!Q", size_packed)[0]
struct.error: unpack requires a string argument of length 8
Unhandled exception in thread started by <bound method Server.__run of <pp.pp.Server object at 0xb38644c>>
job.finalize(sresult)
UnboundLocalErrorTraceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/pp/pp.py", line 775, in __run
: local variable 'sresult' referenced before assignment
    job.finalize(sresult)
UnboundLocalError: local variable 'sresult' referenced before assignment

**Comment by zli-nflx** [comment]
From the error messages, it seems the 'make' has failed. Have you seen any
error messages while 'make'? If succeeded, you should see executables such
as 'vmaf' generated under feature directory.

**Comment by xbfhuawei** [comment]
Hi,
   sor I ignored the err when making.Here is the err of 'make',
root@ubuntu:~/Desktop/vmaf-master# make
for dir in feature libsvm; do \
                cd ${dir}; make; cd ..; \
        done
make[1]: Entering directory `/root/Desktop/vmaf-master/feature'
cc -c -o /root/Desktop/vmaf-master/feature/obj/adm_tools.o -std=c99 -g -O3 -fPIC -Wall -Wextra -pedantic   /root/Desktop/vmaf-master/feature/src/adm_tools.c
In file included from /root/Desktop/vmaf-master/feature/src/adm_tools.c:32:0:
/usr/lib/gcc/i686-linux-gnu/4.6/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"
/root/Desktop/vmaf-master/feature/src/adm_tools.c: In function â€˜rcp_sâ€™:
/root/Desktop/vmaf-master/feature/src/adm_tools.c:36:2: warning: implicit declaration of function â€˜_mm_cvtss_f32â€™ [-Wimplicit-function-declaration]
/root/Desktop/vmaf-master/feature/src/adm_tools.c:36:2: warning: implicit declaration of function â€˜_mm_rcp_ssâ€™ [-Wimplicit-function-declaration]
/root/Desktop/vmaf-master/feature/src/adm_tools.c:36:2: warning: implicit declaration of function â€˜_mm_load_ssâ€™ [-Wimplicit-function-declaration]
/root/Desktop/vmaf-master/feature/src/adm_tools.c: In function â€˜rcp_dâ€™:
/root/Desktop/vmaf-master/feature/src/adm_tools.c:42:2: error: unknown type name â€˜__m128dâ€™
/root/Desktop/vmaf-master/feature/src/adm_tools.c:42:2: warning: implicit declaration of function â€˜_mm_load_sdâ€™ [-Wimplicit-function-declaration]
/root/Desktop/vmaf-master/feature/src/adm_tools.c:43:2: warning: implicit declaration of function â€˜_mm_cvtsd_ssâ€™ [-Wimplicit-function-declaration]
/root/Desktop/vmaf-master/feature/src/adm_tools.c:43:2: warning: implicit declaration of function â€˜_mm_setzero_psâ€™ [-Wimplicit-function-declaration]
make[1]: *** [/root/Desktop/vmaf-master/feature/obj/adm_tools.o] Error 1
make[1]: Leaving directory `/root/Desktop/vmaf-master/feature'
make[1]: Entering directory `/root/Desktop/vmaf-master/libsvm'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/Desktop/vmaf-master/libsvm'
cd libsvm; make lib; cd ..;
make[1]: Entering directory `/root/Desktop/vmaf-master/libsvm'
if [ "Linux" = "Darwin" ]; then \
                SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so.2"; \
        else \
                SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so.2"; \
        fi; \
        g++ ${SHARED_LIB_FLAG} svm.o -o libsvm.so.2
make[1]: Leaving directory `/root/Desktop/vmaf-master/libsvm'
root@ubuntu:~/Desktop/vmaf-master#

But I just copy the project and make,why it can not be done?

**Comment by zli-nflx** [comment]
It looks like the issue is "SSE2 instruction set not enabled". What cpu architecture are you using?
Googling this topic leads to:
https://github.com/shogun-toolbox/shogun/issues/2199
http://stackoverflow.com/questions/9144545/sse-instruction-set-not-enabled

Perhaps your gcc/g++ is out of date? Can you try the tips above to see if they work?

**Comment by xbfhuawei** [comment]
Hi
  Now there are no buiding errs.But when try ./unitest:
======================================================================
ERROR: feature_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: feature_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/feature/test/feature_test.py", line 9, in <module>
    import config
ImportError: No module named config


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Run tests in python/test...
EEEEEEEEE
======================================================================
ERROR: quality_runner_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: quality_runner_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/quality_runner_test.py", line 7, in <module>
    from core.asset import Asset
ImportError: No module named core.asset


======================================================================
ERROR: cross_validation_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: cross_validation_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/cross_validation_test.py", line 8, in <module>
    from core.train_test_model import RandomForestTrainTestModel, LibsvmnusvrTrainTestModel
ImportError: No module named core.train_test_model


======================================================================
ERROR: asset_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: asset_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/asset_test.py", line 7, in <module>
    import config
ImportError: No module named config


======================================================================
ERROR: routine_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: routine_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/routine_test.py", line 7, in <module>
    import config
ImportError: No module named config


======================================================================
ERROR: feature_extractor_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: feature_extractor_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/feature_extractor_test.py", line 8, in <module>
    import config
ImportError: No module named config


======================================================================
ERROR: reader_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: reader_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/reader_test.py", line 8, in <module>
    import config
ImportError: No module named config


======================================================================
ERROR: result_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: result_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/result_test.py", line 9, in <module>
    from core.asset import Asset
ImportError: No module named core.asset


======================================================================
ERROR: train_test_model_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: train_test_model_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/train_test_model_test.py", line 10, in <module>
    import config
ImportError: No module named config


======================================================================
ERROR: feature_assembler_test (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: feature_assembler_test
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/root/Desktop/vmaf-master/python/test/feature_assembler_test.py", line 6, in <module>
    from core.asset import Asset
ImportError: No module named core.asset


----------------------------------------------------------------------
Ran 9 tests in 0.001s


or try :./run_vmaf yuv420p 576 324 resource/yuv/src01_hrc00_576x324.yuv resource/yuv/src01_hrc01_576x324.yuv

Traceback (most recent call last):
  File "python/run_vmaf.py", line 11, in <module>
    from core.quality_runner import VmafQualityRunner
  File "/root/Desktop/vmaf-master/python/core/quality_runner.py", line 14, in <module>
    from core.train_test_model import TrainTestModel
  File "/root/Desktop/vmaf-master/python/core/train_test_model.py", line 572, in <module>
    class LibsvmnusvrTrainTestModel(TrainTestModel):
  File "/root/Desktop/vmaf-master/python/core/train_test_model.py", line 578, in LibsvmnusvrTrainTestModel
    import svmutil
  File "/root/Desktop/vmaf-master/libsvm/python/svmutil.py", line 5, in <module>
    from svm import *
  File "/root/Desktop/vmaf-master/libsvm/python/svm.py", line 22, in <module>
    raise Exception('LIBSVM library not found.')
Exception: LIBSVM library not found.
root@ubuntu:~/Desktop/vmaf-master# ./run_vmaf yuv420p 576 324 resource/yuv/src01_hrc00_576x324.yuv resource/yuv/src01_hrc01_576x324.yuv
Traceback (most recent call last):
  File "python/run_vmaf.py", line 11, in <module>
    from core.quality_runner import VmafQualityRunner
  File "/root/Desktop/vmaf-master/python/core/quality_runner.py", line 14, in <module>
    from core.train_test_model import TrainTestModel
  File "/root/Desktop/vmaf-master/python/core/train_test_model.py", line 572, in <module>
    class LibsvmnusvrTrainTestModel(TrainTestModel):
  File "/root/Desktop/vmaf-master/python/core/train_test_model.py", line 578, in LibsvmnusvrTrainTestModel
    import svmutil
  File "/root/Desktop/vmaf-master/libsvm/python/svmutil.py", line 5, in <module>
    from svm import *
  File "/root/Desktop/vmaf-master/libsvm/python/svm.py", line 22, in <module>
    raise Exception('LIBSVM library not found.')
Exception: LIBSVM library not found.
root@ubuntu:~/Desktop/vmaf-master#

thks.

**Comment by xbfhuawei** [comment]
Hi,
   Now I update the gcc g++ and no building errs .But try ./unitest  err:

Exception: LIBSVM library not found.


======================================================================
ERROR: test_feature_assembler_selected_atom_feature (feature_assembler_test.FeatureAssemblerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/test/feature_assembler_test.py", line 94, in test_feature_assembler_selected_atom_feature
    self.fassembler.run()
  File "/root/Desktop/vmaf-master/python/core/feature_assembler.py", line 70, in run
    optional_dict=self.optional_dict,
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 415, in run_executors_in_parallel
    results = [executor.results[0] for executor in executors]
AttributeError: 'NoneType' object has no attribute 'results'

======================================================================
ERROR: test_feature_assembler_whole_feature (feature_assembler_test.FeatureAssemblerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/test/feature_assembler_test.py", line 53, in test_feature_assembler_whole_feature
    self.fassembler.run()
  File "/root/Desktop/vmaf-master/python/core/feature_assembler.py", line 70, in run
    optional_dict=self.optional_dict,
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 415, in run_executors_in_parallel
    results = [executor.results[0] for executor in executors]
AttributeError: 'NoneType' object has no attribute 'results'

======================================================================
FAIL: test_run_psnr_fextractor (feature_extractor_test.FeatureExtractorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/test/feature_extractor_test.py", line 248, in test_run_psnr_fextractor
    self.fextractor.run()
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 63, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 207, in _run_on_asset
    result = self._read_result(asset)
  File "/root/Desktop/vmaf-master/python/core/feature_extractor.py", line 32, in _read_result
    result.update(self._get_feature_scores(asset))
  File "/root/Desktop/vmaf-master/python/core/feature_extractor.py", line 266, in _get_feature_scores
    assert len(psnr_scores) != 0
AssertionError

======================================================================
FAIL: test_run_vamf_fextractor (feature_extractor_test.FeatureExtractorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/test/feature_extractor_test.py", line 65, in test_run_vamf_fextractor
    self.fextractor.run()
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 63, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 207, in _run_on_asset
    result = self._read_result(asset)
  File "/root/Desktop/vmaf-master/python/core/feature_extractor.py", line 32, in _read_result
    result.update(self._get_feature_scores(asset))
  File "/root/Desktop/vmaf-master/python/core/feature_extractor.py", line 119, in _get_feature_scores
    assert len_score != 0
AssertionError

======================================================================
FAIL: test_run_vamf_fextractor_with_result_store (feature_extractor_test.FeatureExtractorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/Desktop/vmaf-master/python/test/feature_extractor_test.py", line 126, in test_run_vamf_fextractor_with_result_store
    self.fextractor.run()
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 63, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/root/Desktop/vmaf-master/python/core/executor.py", line 207, in _run_on_asset
    result = self._read_result(asset)
  File "/root/Desktop/vmaf-master/python/core/feature_extractor.py", line 32, in _read_result
    result.update(self._get_feature_scores(asset))
  File "/root/Desktop/vmaf-master/python/core/feature_extractor.py", line 119, in _get_feature_scores
    assert len_score != 0
AssertionError

----------------------------------------------------------------------
Ran 40 tests in 1.536s

FAILED (failures=3, errors=9)

It suggest that LIBSVM library not found. Why?

**Comment by zli-nflx** [comment]
If you cd to libsvm, and 'make clean; make' from there, does the build pass? I suspect that there is error(s) when you build.
