### ISSUE TITLE
v1.5.1 does not build on Homebrew

### ISSUE THREAD

**Issue by slhck** [Netflix/vmaf#510]
Adding this here to keep track of https://github.com/Homebrew/homebrew-core/pull/50811.

Homebrew cannot write the models to the default path, so this error is raised:

```
==> make install INSTALL_PREFIX=/usr/local/Cellar/libvmaf/1.5.1
mkdir -p libvmaf/build && cd libvmaf/build && \
	meson .. --buildtype release && \
	ninja -vC . install
Directory already configured.

Just run your build command (e.g. ninja) and Meson will regenerate as necessary.
If ninja fails, run "ninja reconfigure" or "meson --reconfigure"
to force Meson to regenerate.

If build failures persist, run "meson setup --wipe" to rebuild from scratch
using the same options as passed when configuring the build.
To change option values, run "meson configure" instead.
ninja: Entering directory `.'
[1/2] /usr/local/Cellar/meson/0.53.2/libexec/bin/meson --internal vcstagger ../include/vcs_version.h.in include/vcs_version.h 1.3.16 /private/tmp/libvmaf-20200228-84674-114m5eh/vmaf-1.5.1/libvmaf/include @VCS_TAG@ '(.*)' /usr/local/Homebrew/Library/Homebrew/shims/mac/super/git --git-dir /private/tmp/libvmaf-20200228-84674-114m5eh/vmaf-1.5.1/libvmaf/../.git describe --tags --long --match '?.*.*' --always
fatal: not a git repository: '/private/tmp/libvmaf-20200228-84674-114m5eh/vmaf-1.5.1/libvmaf/../.git'
[1/2] /usr/local/Cellar/meson/0.53.2/libexec/bin/meson install --no-rebuild
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/mesonmain.py", line 129, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 514, in run
    installer.do_install(datafilename)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 341, in do_install
    self.install_subdirs(d) # Must be first, because it needs to delete the old subtree.
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 364, in install_subdirs
    d.dirmaker.makedirs(full_dst_dir, exist_ok=True)
  File "/usr/local/lib/python3.7/site-packages/mesonbuild/minstall.py", line 55, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/usr/local/share/model'
Installing subdir /private/tmp/libvmaf-20200228-84674-114m5eh/vmaf-1.5.1/libvmaf/../model to /usr/local/share/model
FAILED: meson-install
/usr/local/Cellar/meson/0.53.2/libexec/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
make: *** [install] Error 1
```

Have to figure out how to make it write the files into the Cellar instead.

**Comment by 1480c1** [comment]
Does Homebrew have a meson function with the correct prefix?

**Comment by slhck** [comment]
I have never used Meson before. It apparently defaults to `/usr/local`. Instead it should be configured to use the `prefix` attribute within the Homebrew formula.

I now notice that of course the formula still uses the old `make` calls. I'll see if I can change that.

**Comment by slhck** [comment]
I've modified the formula to use the correct Meson commands. So this error seems to be fixed.

Now all that's missing is a proper test. I think the issue is that during the `test` run, you don't have access to the build sources, but then again I haven't really used Homebrew's testing before either. I'll investigate.

**Comment by slhck** [comment]
I added a simple test that includes `libvmaf.h`, but that is probably not enough to ensure functionality. Ideally, the model file should be loaded to check whether the file is accessible.

**Comment by 1480c1** [comment]
One problem I can already see when packaging this is that the default model path is hardcoded in ffmpeg and vmafosexec

**Comment by slhck** [comment]
Yes, this is related to https://github.com/Netflix/vmaf/issues/324

**Comment by slhck** [comment]
I think I got it to work with a simple test. Closing for now.

PS, @1480c1 – you can get the path at runtime when using Homebrew, which works more or less fine, see e.g. here https://github.com/slhck/ffmpeg-quality-metrics/blob/master/ffmpeg_quality_metrics/__main__.py#L38
