### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by juanpef** [Netflix/vmaf#81]
When I run:

./run_vmaf yuv420p 576 324 python/test/resource/yuv/src01_hrc00_576x324.yuv python/test/resource/yuv/src01_hrc01_576x324.yuv --out-fmt json

I get an AsserionError:

**Illegal instruction
Traceback (most recent call last):
  File "./run_vmaf", line 143, in <module>
    ret = main()
  File "./run_vmaf", line 107, in main
    runner.run()
  File "/home/ubuntu/vmaf/python/src/vmaf/core/executor.py", line 120, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/quality_runner.py", line 311, in _run_on_asset
    vmaf_fassembler.run()
  File "/home/ubuntu/vmaf/python/src/vmaf/core/feature_assembler.py", line 82, in run
    runner.run(parallelize=self.parallelize)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/executor.py", line 120, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/executor.py", line 286, in _run_on_asset
    self._generate_result(asset)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/feature_extractor.py", line 162, in _generate_result
    run_process(vmaf_feature_cmd, shell=True)
  File "/home/ubuntu/vmaf/python/src/vmaf/tools/misc.py", line 374, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 132, cmd: /home/ubuntu/vmaf/feature/vmaf all yuv420p python/test/resource/yuv/src01_hrc00_576x324.yuv python/test/resource/yuv/src01_hrc01_576x324.yuv 576 324 >> /home/ubuntu/vmaf/workspace/workdir/c40e5bb6-9542-45af-92cf-f6e0f37f1d58/VMAF_feature_V0.2.4b_ef6af54084b6d2f6fd4ad0c6c2301830c53a9abf**

What could be the problem?

Thanks

**Comment by li-zhi** [comment]
Hi,

If you run:

*/home/ubuntu/vmaf/feature/vmaf all yuv420p
python/test/resource/yuv/src01_hrc00_576x324.yuv
python/test/resource/yuv/src01_hrc01_576x324.yuv 576 324*

*under the same directory, what's the message given to you?*

**Comment by juanpef** [comment]
Thanks for your answer @li-zhi ,
I have run these instruction getting:
**Illegal instruction**

**Comment by juanpef** [comment]
Thanks for your answer @li-zhi ,
I have run these instruction getting:
**Illegal instruction**

**Comment by ecomte** [comment]
./run_vmaf yuv420p 576 324 /vmaf/python/test/resource/yuv/src01_hrc00_576x324.yuv /vmaf/python/test/resource/yuv/src01_hrc01_576x324.yuv --out-fmt json

Try running that, not sure if that will change things or not; that's just how I've been running it.
