### ISSUE TITLE
./unittest error

### ISSUE THREAD

**Issue by juanpef** [Netflix/vmaf#83]
I get an error when execute ./unittest:

**AssertionError: Process returned 132, cmd: /home/ubuntu/vmaf/feature/ssim yuv420p /home/ubuntu/vmaf/python/test/resource/yuv/src01_hrc00_576x324.yuv /home/ubuntu/vmaf/python/test/resource/yuv/src01_hrc00_576x324.yuv 576 324 >> /home/ubuntu/vmaf/workspace/workdir/1912e6a0-5fdd-4824-a5ad-d8407b3e5eb4/SSIM_feature_V1.1_522f1dc24a70f694b7b4f7cdbdae1eb3ce2c6b0e
Illegal instruction
Process Process-100:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/vmaf/python/src/vmaf/tools/misc.py", line 258, in func_wrapper
    executor = func(args)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/executor.py", line 114, in _run
    result = self._run_on_asset(asset)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/quality_runner.py", line 574, in _run_on_asset
    vmaf_fassembler.run()
  File "/home/ubuntu/vmaf/python/src/vmaf/core/feature_assembler.py", line 82, in run
    runner.run(parallelize=self.parallelize)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/executor.py", line 120, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/executor.py", line 286, in _run_on_asset
    self._generate_result(asset)
  File "/home/ubuntu/vmaf/python/src/vmaf/core/feature_extractor.py", line 473, in _generate_result
    run_process(ssim_cmd, shell=True)
  File "/home/ubuntu/vmaf/python/src/vmaf/tools/misc.py", line 374, in run_process
    assert ret == 0, 'Process returned {ret}, cmd: {cmd}'.format(ret=ret, cmd=cmd)
AssertionError: Process returned 132, cmd: /home/ubuntu/vmaf/feature/ssim yuv420p /home/ubuntu/vmaf/python/test/resource/yuv/src01_hrc00_576x324.yuv /home/ubuntu/vmaf/python/test/resource/yuv/src01_hrc01_576x324.yuv 576 324 >> /home/ubuntu/vmaf/workspace/workdir/b41d1ce1-72bf-49f0-b669-3bf504d35617/SSIM_feature_V1.1_83453789ae2c5a4e39f5cce9d1c7c8a1c09a62ac**

Somebody knows what could be the problem?

Thanks in advance

**Comment by li-zhi** [comment]
@juanpef Please paste the output after running the cmd below:

/home/ubuntu/vmaf/feature/ssim yuv420p /home/ubuntu/vmaf/python/test/resource/yuv/src01_hrc00_576x324.yuv /home/ubuntu/vmaf/python/test/resource/yuv/src01_hrc00_576x324.yuv 576 324
