### ISSUE TITLE
FAILED (errors=3)

### ISSUE THREAD

**Issue by xbfhuawei** [Netflix/vmaf#9]
Hi，
    Now I have succeed buiding the project.The version of the python and packages are:

numpy:1.11.0
scipy:0.13.3
matplotlib:1.3.1
pandas:0.13.1
sklearn:0.18.0

some packages can not update to newest version.

now I run :./unittest got 3 errs:
======================================================================
ERROR: test_run_parallel_vamf_runner_with_model (quality_runner_test.ParallelQualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xbf/Desktop/vmaf-master/python/test/quality_runner_test.py", line 534, in test_run_parallel_vamf_runner_with_model
    'model_filepath':config.ROOT + "/resource/model/nflx_vmaff_rf_v1.pkl",
  File "/home/xbf/Desktop/vmaf-master/python/core/executor.py", line 415, in run_executors_in_parallel
    results = [executor.results[0] for executor in executors]
AttributeError: 'NoneType' object has no attribute 'results'

======================================================================
ERROR: test_run_vmaf_runner_with_rf_model (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xbf/Desktop/vmaf-master/python/test/quality_runner_test.py", line 393, in test_run_vmaf_runner_with_rf_model
    self.runner.run()
  File "/home/xbf/Desktop/vmaf-master/python/core/executor.py", line 63, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/home/xbf/Desktop/vmaf-master/python/core/quality_runner.py", line 276, in _run_on_asset
    vmaf_fassembler = self._get_vmaf_feature_assembler_instance(asset)
  File "/home/xbf/Desktop/vmaf-master/python/core/quality_runner.py", line 253, in _get_vmaf_feature_assembler_instance
    model = self._load_model()
  File "/home/xbf/Desktop/vmaf-master/python/core/quality_runner.py", line 356, in _load_model
    model = TrainTestModel.from_file(model_filepath, self.logger)
  File "/home/xbf/Desktop/vmaf-master/python/core/train_test_model.py", line 144, in from_file
    info_loaded = pickle.load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
  File "sklearn/tree/_tree.pyx", line 629, in sklearn.tree._tree.Tree.__setstate__ (sklearn/tree/_tree.c:7698)
KeyError: 'max_depth'

======================================================================
ERROR: test_run_vmaf_runner_with_rf_model (quality_runner_test.QualityRunnerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/xbf/Desktop/vmaf-master/python/test/quality_runner_test.py", line 19, in tearDown
    self.runner.remove_results()
  File "/home/xbf/Desktop/vmaf-master/python/core/executor.py", line 72, in remove_results
    self._remove_result(asset)
  File "/home/xbf/Desktop/vmaf-master/python/core/quality_runner.py", line 363, in _remove_result
    vmaf_fassembler = self._get_vmaf_feature_assembler_instance(asset)
  File "/home/xbf/Desktop/vmaf-master/python/core/quality_runner.py", line 253, in _get_vmaf_feature_assembler_instance
    model = self._load_model()
  File "/home/xbf/Desktop/vmaf-master/python/core/quality_runner.py", line 356, in _load_model
    model = TrainTestModel.from_file(model_filepath, self.logger)
  File "/home/xbf/Desktop/vmaf-master/python/core/train_test_model.py", line 144, in from_file
    info_loaded = pickle.load(file)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1217, in load_build
    setstate(state)
  File "sklearn/tree/_tree.pyx", line 629, in sklearn.tree._tree.Tree.__setstate__ (sklearn/tree/_tree.c:7698)
KeyError: 'max_depth'

----------------------------------------------------------------------
Ran 69 tests in 147.923s

FAILED (errors=3)

ps.python version：2.7.6

Why  and how can I solve this problems. I almost go creazy！ Thx！

**Comment by zli-nflx** [comment]
Can you upgrade your packages to the latest and try again?

**Comment by eexyzhang** [comment]
I also got similar errors when running ./unittest

The version of my packages are:
- numpy (1.11.1)
- scipy (0.18.1)
- matplotlib (1.5.3)
- pandas (0.18.1)
- scikit-learn (0.18)
- h5py (2.6.0)

Part of the screen print is as follows:

.................test cross validation...
.test k-fold cross validation on extra trees...
.test k-fold cross validation on libsvmnusvr...
.test k-fold cross validation on random forest...
.test k-fold cross validation with list input...
.test nested k-fold cross validation on libsvmnusvr...
.test nested k-fold cross validation on random forest...
.test nested k-fold cross validation with list input...
...test on feature assembler with selected atom features...
.test on feature assembler with whole feature...
....test on running Moment feature extractor...
.test on running MS-SSIM feature extractor...
.test on running PSNR feature extractor...
.test on running SSIM feature extractor...
.test on running VMAF feature extractor...
.test on running VMAF feature extractor with result store...
    running for the first time with fresh calculation...
    running for the second time with stored results...
..test on running Moment feature extractor in parallel...
.test on running MS-SSIM feature extractor in parallel...
.test on running SSIM feature extractor in parallel...
.test on running VMAF feature extractor in parallel...
.test on running VMAF feature extractor with result store in parallel...
    running for the first time with fresh calculation...
    running for the second time with stored results...
...test on running VMAF runner with local explainer...
.test on running Moment noref feature extractor on Assets...
.test on running Moment noref feature extractor on NorefAssets...
.test on running Moment noref feature extractor on NorefAssets in parallel...
.test on running MS-SSIM quality runner in parallel...
.test on running PSNR quality runner in parallel...
.test on running SSIM quality runner in parallel...
.test on running VMAF quality runner in parallel with RF model...
/Users/abc/software/anaconda2/lib/python2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version pre-0.18 when using version 0.18. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
An error has occured during the function execution
Traceback (most recent call last):
  File "/Users/abc/Netflix_VMAF/vmaf/python/pp/ppworker.py", line 100, in run
    __result = __f(*__args)
  File "<string>", line 7, in run_executor
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 81, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 286, in _run_on_asset
    vmaf_fassembler = self._get_vmaf_feature_assembler_instance(asset)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 262, in _get_vmaf_feature_assembler_instance
    feature_dict = self._load_model(asset).get_appended_info('feature_dict')
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 338, in _load_model
    model = TrainTestModel.from_file(model_filepath, self.logger)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/train_test_model.py", line 326, in from_file
    info_loaded = pickle.load(file)
  File "/Users/abc/software/anaconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/Users/abc/software/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Users/abc/software/anaconda2/lib/python2.7/pickle.py", line 1223, in load_build
    setstate(state)
  File "sklearn/tree/_tree.pyx", line 633, in sklearn.tree._tree.Tree.__setstate__ (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-EIz_8i-build/sklearn/tree/_tree.c:7860)
KeyError: 'max_depth'
/Users/abc/software/anaconda2/lib/python2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version pre-0.18 when using version 0.18. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
An error has occured during the function execution
Traceback (most recent call last):
  File "/Users/abc/Netflix_VMAF/vmaf/python/pp/ppworker.py", line 100, in run
    __result = __f(*__args)
  File "<string>", line 7, in run_executor
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/executor.py", line 81, in run
    self.results = map(self._run_on_asset, self.assets)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 286, in _run_on_asset
    vmaf_fassembler = self._get_vmaf_feature_assembler_instance(asset)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 262, in _get_vmaf_feature_assembler_instance
    feature_dict = self._load_model(asset).get_appended_info('feature_dict')
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/quality_runner.py", line 338, in _load_model
    model = TrainTestModel.from_file(model_filepath, self.logger)
  File "/Users/abc/Netflix_VMAF/vmaf/python/core/train_test_model.py", line 326, in from_file
    info_loaded = pickle.load(file)
  File "/Users/abc/software/anaconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/Users/abc/software/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Users/abc/software/anaconda2/lib/python2.7/pickle.py", line 1223, in load_build
    setstate(state)
  File "sklearn/tree/_tree.pyx", line 633, in sklearn.tree._tree.Tree.__setstate__ (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-EIz_8i-build/sklearn/tree/_tree.c:7860)
KeyError: 'max_depth'
Etest on running VMAF (legacy) quality runner in parallel...
..test on running MS-SSIM runner...
.test on running PSNR runner...
.test on running SSIM runner...

**Comment by li-zhi** [comment]
@eexyzhang: it looks like the latest sklearn (0.18) is not backward-compatible with models generated by previous versions. I've updated the failed test case to make it compatible with sklearn 0.18. Please pull the master and re-run the unittest.

**Comment by eexyzhang** [comment]
Thanks, the update solves the problem of 'max_depth'.

**Comment by prateekpatelsc** [comment]
Hi Can you tell what versions are you using that solves the problem. I am running into same issue. Thanks

**Comment by li-zhi** [comment]
@prateekpatelsc If you run:
python -c 'import sklearn as pkg; print pkg.__version__; print pkg.__file__'
You should get version number 0.18.

**Comment by prateekpatelsc** [comment]
i am actually using the latest version (0.18 for scikit-learn)  on a docker image and running into the key_error : max_depth:
RUN pip install pandas==0.19.0
RUN pip install numpy==1.11.2
RUN pip install scipy==0.18.1
RUN pip install sklearn_pandas
RUN pip install scikit-learn==0.18.0

Are these the correct versions ?
